env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_task:
  matrix:
    - name: 13.0-CURRENT
      freebsd_instance:
        image_family: freebsd-13-0-snap
    - name: 12.2-STABLE
      freebsd_instance:
        image_family: freebsd-12-2-snap
    - name: 12.1-RELEASE
      freebsd_instance:
        image_family: freebsd-12-1
    - name: 11.4-RELEASE
      freebsd_instance:
        image_family: freebsd-11-4
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y git-lite py27-yaml
  script:
    - fetch http://tetworks.opengroup.org/downloads/38/software/Sources/3.8/tet3.8-src.tar.gz
    - tar -x -C test/tet -f tet3.8-src.tar.gz
    - make
  test_script:
    - make run-tests

ubuntu_task:
  container:
    image: ubuntu:18.04
  setup_script:
    - apt-get update
    - apt-get install -y
      binutils bison bmake curl flex g++ gcc git
      libarchive-dev libbsd-dev libc6-dev libexpat1-dev lsb-release
      m4 perl python-yaml sharutils zlib1g-dev
  script:
    - curl -O http://tetworks.opengroup.org/downloads/38/software/Sources/3.8/tet3.8-src.tar.gz
    - tar -x -C test/tet -z -f tet3.8-src.tar.gz
    - bmake
  test_script:
    - bmake run-tests
